=== fsoc1ety/xml-basics/data/timetable.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- A timetable will have the term, set, periods, instructors, and daysofweek -->
<!ELEMENT timetable (
        term, 
        set, 
        periods, 
        instructors,
        daysofweek
        )>

<!-- A term is determined by the timetable -->
<!ELEMENT term (#PCDATA)>
<!-- A set is determined by the timetable -->
<!ELEMENT set (#PCDATA)>

<!-- A period consists of blocks -->
<!ELEMENT periods (block*)>
<!-- A block consists of classes -->
<!ELEMENT block (class*)>
<!-- A block time requires field named time to be filled -->
<!ATTLIST block time CDATA #REQUIRED>

<!-- A instructors consists of instructor -->
<!ELEMENT instructors (instructor*)>
<!-- A instructor consists of classes -->
<!ELEMENT instructor (class*)>
<!-- A instructor name requires field named name to be filled -->
<!ATTLIST instructor name CDATA #REQUIRED>

<!-- A daysofweek consists of day -->
<!ELEMENT daysofweek (day*)>
<!-- A day consists of classes -->
<!ELEMENT day (class*)>
<!-- A day name requires field named name to be filled -->
<!ATTLIST day name CDATA #REQUIRED>

<!-- A class will have the name, code, location, and have either dayofclass and classinstructor -->
<!ELEMENT class (  
        name,
        code,
        dayofclass?,
        classinstructor?,
        location,
        type
        )>

<!-- A class will have its day and time implied -->
<!ATTLIST class 
        day CDATA #IMPLIED 
        time CDATA #IMPLIED
        >
        
<!-- A dayofclass will have its value determined by a string -->
<!ELEMENT dayofclass (#PCDATA)>
<!-- A name will have its value determined by a string -->
<!ELEMENT name (#PCDATA)>
<!-- A code will have its value determined by a string -->
<!ELEMENT code (#PCDATA)>
<!-- A classinstructor will have its value determined by a string -->
<!ELEMENT classinstructor (#PCDATA)>
<!-- A location will have its value determined by a string -->
<!ELEMENT location (#PCDATA)>
<!-- A type will have its value determined by a string -->
<!ELEMENT type (#PCDATA)>

=== fsoc1ety/xml-basics/data/timetable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timetable SYSTEM "timetable.dtd">
<timetable>
    <term>Winter-2016</term>
    <set>4G</set>
    <periods>
        <block time="8:30">
            <class day="Monday">
                <name>Computer Graphics</name>
                <code>COMP4560</code>
                <classinstructor>Brenda Fine</classinstructor>
                <location>SE12-320</location>
                <type>Lab</type>  
            </class>
            <class day="Friday">
                <name>Business Law</name>
                <code>BLAW3600</code>
                <classinstructor>Catherine Ryan</classinstructor>
                <location>SW5-1840</location>
                <type>Lecture</type>
            </class>
        </block>
        <block time="9:30">
            <class day="Wednesday">
                <name>Client Server Special Topics</name>
                <code>COMP4945</code>
                <classinstructor>Tejinder Randhawa</classinstructor>
                <location>SE12-319</location>
                <type>Lecture</type>
            </class>
            <class day="Thursday">
                <name>Business Law</name>
                <code>BLAW3600</code>
                <classinstructor>Catherine Ryan</classinstructor>
                <location>SW3-2620</location>
                <type>Lab</type>
            </class>
        </block>
        <block time="10:30">
            <class day="Wednesday">
                <name>Client Server 2</name>
                <code>COMP4941</code>
                <classinstructor>Tejinder Randhawa</classinstructor>
                <location>SE12-319</location>
                <type>Lab</type>
            </class>
        </block>
        <block time="11:30">
            <class day="Monday">
                <name>Operating Systems</name>
                <code>COMP4735</code>
                <classinstructor>Mirela Gutica</classinstructor>
                <location>SW1-1205</location>
                <type>Lecture</type>
            </class>
            <class day="Tuesday">
                <name>Computer Graphics</name>
                <code>COMP4560</code>
                <classinstructor>Brenda Fine</classinstructor>
                <location>SW5-1850</location>
                <type>Lecture</type>
            </class>
            <class day="Thursday">
                <name>Operating Systems</name>
                <code>COMP4735</code>
                <classinstructor>Mirela Gutica</classinstructor>
                <location>SW3-1710</location>
                <type>Lecture</type>
            </class>
        </block>
        <block time="12:30">
            <class day="Friday">
                <name>Computer Graphics</name>
                <code>COMP4560</code>
                <classinstructor>Brenda Fine</classinstructor>
                <location>SW3-1750</location>
                <type>Lecture</type>
            </class>  
            <class day="Tuesday">
                <name>Software Development</name>
                <code>COMP4711</code>
                <classinstructor>Jim Parry</classinstructor>
                <location>SE12-320</location>
                <type>Lab</type>
            </class>
        </block>
        <block time="1:30">
            <class day="Wednesday">
                <name>Operating Systems</name>
                <code>COMP4735</code>
                <classinstructor>Mirela Gutica</classinstructor>
                <location>SW1-1205</location>
                <type>Lecture</type>
            </class>            
            <class day="Thursday">
                <name>Client Server Special Topics</name>
                <code>COMP4945</code>
                <classinstructor>Tejinder Randhawa</classinstructor>
                <location>SE12-319</location>
                <type>Lab</type>
            </class>
            <class day="Friday">
                <name>Client Server 2</name>
                <code>COMP4941</code>
                <classinstructor>Tejinder Randhawa</classinstructor>
                <location>SE12-319</location>
                <type>Lecture</type>
            </class>           
        </block>
        <block time="2:30">
            <class day="Tuesday">
                <name>Software Development</name>
                <code>COMP4711</code>
                <classinstructor>Jim Parry</classinstructor>
                <location>SW5-1840</location>
                <type>Lecture</type>
            </class>
        </block>
        <block time="3:30">
            <class day="Monday">
                <name>Operating Systems</name>
                <code>COMP4735</code>
                <classinstructor>Mathew Linder</classinstructor>
                <location>SW3-1710</location>
                <type>Lab</type>
            </class>            
        </block>
    </periods>
    
    <instructors>
        <instructor name="Brenda Fine">
            <class time="8:30">
                <name>Computer Graphics</name>
                <code>COMP4560</code>
                <dayofclass>Monday</dayofclass>
                <location>SE12-320</location>
                <type>Lab</type>
            </class>
            <class time="11:30">
                <name>Computer Graphics</name>
                <code>COMP4560</code>
                <dayofclass>Tuesday</dayofclass>
                <location>SW5-1850</location>
                <type>Lecture</type>
            </class>
            <class time="12:30">
                <name>Computer Graphics</name>
                <code>COMP4560</code>
                <dayofclass>Friday</dayofclass>
                <location>SW3-1750</location>
                <type>Lecture</type>
            </class>
        </instructor>
        <instructor name="Mirela Gutica">
            <class time="11:30">
                <name>Operating Systems</name>
                <code>COMP4735</code>
                <dayofclass>Monday</dayofclass>
                <location>SW1-1205</location>
                <type>Lecture</type>
            </class>
            <class time="1:30">
                <name>Operating Systems</name>
                <code>COMP4735</code>
                <dayofclass>Wednesday</dayofclass>
                <location>SW1-1205</location>
                <type>Lecture</type>
            </class>
            <class time="11:30">
                <name>Operating Systems</name>
                <code>COMP4735</code>
                <dayofclass>Thursday</dayofclass>
                <location>SW3-1710</location>
                <type>Lecture</type>
            </class>    
        </instructor>
        <instructor name="Mathew Linder">
            <class time="3:30">
                <name>Operating Systems</name>
                <code>COMP4735</code>
                <dayofclass>Monday</dayofclass>
                <location>SW3-1710</location>
                <type>Lab</type>
            </class>    
        </instructor>
        <instructor name="Tejinder Randhawa">
            <class time="9:30">
                <name>Client Server Special Topics</name>
                <code>COMP4945</code>
                <dayofclass>Wednesday</dayofclass>
                <location>SE12-319</location>
                <type>Lecture</type>
            </class>
            <class time="10:30">
                <name>Client Server 2</name>
                <code>COMP4941</code>
                <dayofclass>Wednesday</dayofclass>
                <location>SE12-319</location>
                <type>Lab</type>
            </class>
            <class time="1:30">
                <name>Client Server Special Topics</name>
                <code>COMP4945</code>
                <dayofclass>Thursday</dayofclass>
                <location>SE12-319</location>
                <type>Lab</type>
            </class>
            <class time="1:30">
                <name>Client Server 2</name>
                <code>COMP4941</code>
                <dayofclass>Friday</dayofclass>
                <location>SE12-319</location>
                <type>Lecture</type>
            </class>      
        </instructor>
        <instructor name="Jim Parry">
            <class time="12:30">
                <name>Software Development</name>
                <code>COMP4711</code>
                <dayofclass>Tuesday</dayofclass>
                <location>SE12-320</location>
                <type>Lab</type>
            </class> 
            <class time="12:30">
                <name>Software Development</name>
                <code>COMP4711</code>
                <dayofclass>Tuesday</dayofclass>
                <location>SW3-1840</location>
                <type>Lecture</type>
            </class> 
        </instructor>
        <instructor name="Catherine Ryan">
            <class time="9:30">
                <name>Business Law</name>
                <code>BLAW3600</code>
                <dayofclass>Thursday</dayofclass>
                <location>SW3-2620</location>
                <type>Lab</type>
            </class>
            <class time="8:30">
                <name>Business Law</name>
                <code>BLAW3600</code>
                <dayofclass>Friday</dayofclass>
                <location>SW5-1840</location>
                <type>Lecture</type>
            </class>
        </instructor>
    </instructors>
    
    <daysofweek>
        <day name="Monday">
            <class time="8:30">
                <name>Computer Graphics</name>
                <code>COMP4560</code>
                <classinstructor>Brenda Fine</classinstructor>
                <location>SE12-320</location>
                <type>Lab</type>
            </class>
            <class time="11:30">
                <name>Operating Systems</name>
                <code>COMP4735</code>
                <classinstructor>Mirela Gutica</classinstructor>
                <location>SW1-1205</location>
                <type>Lecture</type>
            </class>
